#!/bin/bash

################################################################################
### Error handling

# trap and abort on Ctrl-c
control_c()
{
  echo "Build aborted"
  exit 1
}
trap control_c SIGINT

# exit if command fails
try()
{
  # run the command
  $@

  # save the exit code
  __exit_code__=$?

  # check the exit code
  if [ $__exit_code__ -ne 0 ] ; then
    exit $__exit_code__
  fi
}

################################################################################
### Actual Script

clear

# go to the root of Raytracer
cd ~/cs488/handin/RayTracer

# if the first argument is wipe, then wipe instead of building
if [ "$1" = "wipe" ] ; then
  rm -rf build
  exit 0
fi

# ensure build/ contains the most up-to-date code
mkdir -p build
cp -ruf src/*  build
cp -ruf lib/*  build
cp -ruf data/* build

# make
cd build
try make $@

# run the executable
echo
echo "Build successful: running executable"
echo
try ./rt

# display the image
echo
echo "Render successful: displaying the image"
echo
xdg-open scene.png

