#!/bin/bash

################################################################################
### Error handling

# trap and abort on Ctrl-c
control_c()
{
  echo "Build aborted"
  exit 1
}
trap control_c SIGINT

# exit if command fails
try()
{
  # run the command
  $@

  # save the exit code
  __exit_code__=$?

  # check the exit code
  if [ $__exit_code__ -ne 0 ] ; then
    exit $__exit_code__
  fi
}

################################################################################
### Actual Script

clear

# go to the root of Raytracer
if [[ `hostname` == "Ultimatum" ]] ; then
  cd ~/dev/RayTracer
else
  cd ~/cs488/handin/RayTracer
fi

# if the first argument is wipe, then wipe instead of building
if [ "$1" = "wipe" ] ; then
  echo "Deleting build/ directory"
  rm -rf build
  exit 0
fi

# ensure build/ contains the most up-to-date code
echo "========================================"
echo "Updating build/ directory"
echo

mkdir -p build
cp -ruf src/*  build
cp -ruf lib/*  build
cp -ruf data/* build

echo

# make
echo "========================================"
echo "Building executable"
echo

cd build
try make $@

echo

# run the executable
echo "========================================"
echo "Running executable"
echo

try ./rt

echo

# display the image
echo "========================================"
echo "Displaying the image"
echo

xdg-open scene.png

echo

